### ISSUE TITLE
Synchronization causes media files to not play at all in a show

### ISSUE THREAD

**Issue by RoboMWM** [oliverdunk/JukeboxAPI#12]
Sorry for all the updates, very difficult to get to the bottom of this....

I've now tested with the `/jukebox show` command, and I think I can confidently say that this is an issue with synchronization. Using the command, most of the time, only Edge would be able to play the media instantly. Sometimes reloading the firefox page caused the one in Edge to pause momentarily (or completely at one point). Getting debug info would be nice, but it looks like for now I'll have to implement my own sort of "show" manager.

---

I tested and observed the following with just Firefox - but then I decided to do the tests while having both Firefox and Edge open. If the song wasn't playing in either of the two browsers, refreshing one of the browsers caused both songs to start playing through both web browsers. So it very likely is the "synchronization" that's taking a tad too long to sync up. Perhaps you could add a field to set a show to not care so much about "exact" synchronization (and instead just send the song over and hope for the best?)

Also, the ability to get "debug" info on the client would be helpful to determine these issues. Sometimes it was the case that Edge always started playing the media file instantly while Firefox took several seconds to start playing the same file (it was in sync with Edge though) if I quickly teleported away and to the designated world (i.e. while the previous song was playing).

---

It seems if I simultaneously add a new player to a show, and play a new media file in the show, the player does not hear the media until they either are re-added to the show or refresh the web client. The song is about 1MB, so I don't think bandwidth is the concern here.

I've waited for at least a full minute or more for the song to play, in case it's trying to "synchronize" (albeit I'm the only one on the server testing it.)

Code for reference: https://github.com/MLG-Fortress/MountainDewritoes/tree/3c4808dc20929faf9c117226a65de9172e7a98e7/src/main/java/me/robomwm/MountainDewritoes/Music

In short:
- I add player to show depending on which world they're in: https://github.com/MLG-Fortress/MountainDewritoes/blob/3c4808dc20929faf9c117226a65de9172e7a98e7/src/main/java/me/robomwm/MountainDewritoes/Music/AtmosphericManager.java#L130 which calls https://github.com/MLG-Fortress/MountainDewritoes/blob/3c4808dc20929faf9c117226a65de9172e7a98e7/src/main/java/me/robomwm/MountainDewritoes/Music/MemeBox.java#L64
- I play a new media file in the "mall" show when a player joins the mall world. Obviously this won't be the case when I fully finish this feature, but just to test, that's what I did. https://github.com/MLG-Fortress/MountainDewritoes/blob/3c4808dc20929faf9c117226a65de9172e7a98e7/src/main/java/me/robomwm/MountainDewritoes/Music/AtmosphericManager.java#L134 which calls https://github.com/MLG-Fortress/MountainDewritoes/blob/3c4808dc20929faf9c117226a65de9172e7a98e7/src/main/java/me/robomwm/MountainDewritoes/Music/MemeBox.java#L52

**Comment by oliverdunk** [comment]
Hey @RoboMWM, are you still able to reproduce? I can't see what could be causing it but would like to come on your server and do some debugging if this is still an issue.

**Comment by RoboMWM** [comment]
No idea, I've since been deprioritizing mcjukebox since most players don't know or don't want to bother with clicking a link to hear stuff. Also because I'm able to produce localized sounds, though I did discover [the limits of that.](https://github.com/MLG-Fortress/MountainDewritoes/blob/master/src/main/java/me/robomwm/MountainDewritoes/Music/AtmosphericMusic.java#L229) I may consider moving back if you add support for using "embedded" external services such as SoundCloud or YouTube (somewhat a la plug.dj)


Along with the transition (back) to a resource pack, I've forgone synchronization, resorting to things like a global timer that plays to all in the world instead of a per-player delayed task/timer, etc.
