### ISSUE TITLE
Slugish connection

### ISSUE THREAD

**Issue by EclecticInventor** [oliverdunk/JukeboxAPI#17]
Sevral users including myself have found that the webpage can take up to a minute to fully connect as of a week or two ago

**Comment by oliverdunk** [comment]
Is this still happening?

**Comment by EclecticInventor** [comment]
Yes, although not as bad as before.

**Comment by oliverdunk** [comment]
Closing this as I believe we've fixed it as much as we can. If it continues to be unexpectedly slow please reopen this.
