### ISSUE TITLE
Null pointer error

### ISSUE THREAD

**Issue by ghost** [oliverdunk/JukeboxAPI#22]
When adding a region by console and then removing it, it gives this null error on PlayerMoveEvent

https://media.discordapp.net/attachments/204690224054403072/451578919070728202/unknown.png

**Comment by AmusedNetwork** [comment]
Same with PlayerQuitEvent
![image](https://user-images.githubusercontent.com/5558617/40811295-8ceeb5ac-6528-11e8-921c-0515e307ee73.png)

and PlayerJoinEvent

![image](https://user-images.githubusercontent.com/5558617/40811318-a320664a-6528-11e8-9b84-44e832eca7ab.png)
