### ISSUE TITLE
Connect to Server Event

### ISSUE THREAD

**Issue by josh-audio** [oliverdunk/JukeboxAPI#3]
It would be very useful to have an event I can use to tell when a user has opened up the Jukebox website so I can know when to start music playing for them.

> JukeboxPlayerConnectEvent

**Comment by M64mc** [comment]
:+1:

**Comment by oliverdunk** [comment]
Hi,

Just wanted to update you on this - we've investigated a little further and will be making some backend changes in the coming months which will eventually add support for exactly this.

Look forward to sharing it with you :)

**Comment by oliverdunk** [comment]
Fixed in #7 ;)
