### ISSUE TITLE
All commands should have @p selector

### ISSUE THREAD

**Issue by Moutard3** [oliverdunk/JukeboxAPI#31]
As they have `@a`, they should have `@p`.

https://github.com/oliverdunk/JukeboxAPI/blob/78c3f5f5e081d1ee4e9db6f9b145f92cb5f19707/src/main/java/net/mcjukebox/plugin/bukkit/commands/JukeboxCommand.java

**Comment by oliverdunk** [comment]
I believe the reason for implementing `@a` was to make it easy to experiment by executing commands in chat. 1.12 supported both `@a` and `@p` in command blocks for all commands, as that was a part of Spigot.

As of 1.13, however, Spigot no longer gives us this for free, so only the `@a` that we explicitly implemented works. We need to see if we can add `@a` and `@p` for all commands, which would likely be easiest as part of a command class rewrite.

**Comment by oliverdunk** [comment]
Closing, as will include as part of fix for #32
