### ISSUE TITLE
Tidy JukeboxCommand.java

### ISSUE THREAD

**Issue by Moutard3** [oliverdunk/JukeboxAPI#32]
The file is growing more and more and begin to be hard to read. It's bad for maintaining, that's why I'm suggesting to tidy it.
We may think of a better way to define commands (a file per command?) or have better comments to find easily which code is doing what, and most of all for which command.

**Comment by oliverdunk** [comment]
As mentioned in the referenced issue, we should use tidying this as an opportunity to reimplement all selectors for 1.13
