### ISSUE TITLE
unable to start sound track with command_block

### ISSUE THREAD

**Issue by thunderlight411** [oliverdunk/JukeboxAPI#34]
Hi,

i have upgraded my world to 1.13.1 and i'm no longer able to play audio tracks that starts from a command_block

a manual start works perfectly with the same command.

version info
CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
MCJukebox version 2.5.3

i hope that this can be fixed

**Comment by oliverdunk** [comment]
Hi @thunderlight411,

I'm afraid that this is due to a change made by Spigot, meaning `@a` and `@p` which used to work no longer do.

I want to add support back as soon as I can, but it means writing code that we didn't have before. As a result, I can't promise when it'll be ready.
