### ISSUE TITLE
NBS Files Support

### ISSUE THREAD

**Issue by Lmmb74** [oliverdunk/JukeboxAPI#6]
Hi, could you please add support for local nbs files?

**Comment by oliverdunk** [comment]
Hi,

I'll need to look into this but I think it's unlikely. The main purpose of MCJukebox is for playing actual MP3 files and similar, and so playing noteblock files might defeat this. I'll certainly take a look though, and will update this issue when I know more.

**Comment by oliverdunk** [comment]
@Lmmb74 Closing this as I can't see this being implemented anytime soon. I will remember your request however in case we ever run out of ideas!
